
redirects:
  develop/creating_stackpacks: ./develop/stackpack/README.md
  integrations/: ./stackpacks/README.md
  integrations/available_stackpacks/: ./stackpacks/README.md
  integrations/available_stackpacks/agent: ./stackpacks/integrations/agent.md
  integrations/available_stackpacks/api-integration: stackpacks/integrations/api-integration.md
  integrations/available_stackpacks/aws: ./stackpacks/integrations/aws.md
  integrations/available_stackpacks/azure: ./stackpacks/integrations/azure.md
  integrations/available_stackpacks/cloudera: ./stackpacks/integrations/cloudera.md
  integrations/available_stackpacks/customsync: ./stackpacks/integrations/customsync.md
  integrations/available_stackpacks/google_analytics: ./stackpacks/integrations/google_analytics.md
  integrations/available_stackpacks/humio: ./stackpacks/integrations/humio.md
  integrations/available_stackpacks/kubernetes: ./stackpacks/integrations/kubernetes.md
  integrations/available_stackpacks/logz: ./stackpacks/integrations/logz.md
  integrations/available_stackpacks/manualtopo: ./stackpacks/integrations/manualtopo.md
  integrations/available_stackpacks/nagios: ./stackpacks/integrations/nagios.md
  integrations/available_stackpacks/openshift: ./stackpacks/integrations/openshft.md
  integrations/available_stackpacks/sap: ./stackpacks/integrations/sap.md
  integrations/available_stackpacks/scom: ./stackpacks/integrations/scom.md
  integrations/available_stackpacks/servicenow: ./stackpacks/integrations/servicenow.md
  integrations/available_stackpacks/splunk: ./stackpacks/integrations/splunk/README.md
  integrations/available_stackpacks/splunk/splunk_event: ./stackpacks/integration/splunk/splunk_event.md
  integrations/available_stackpacks/splunk/splunk_metric: ./stackpacks/integrations/splunk/splunk_metric.md
  integrations/available_stackpacks/static_topology: ./stackpacks/integrations/static_topology.md
  integrations/available_stackpacks/vsphere: ./stackpacks/integrations/vsphere.md
  integrations/available_stackpacks/zabbixL: ./stackpacks/integrations/zabbix.md
  integrations/introduction: ./stackpacks/about-stackpacks.md
  integrations/mirrors: ./develop/mirrors/README.md
  integrations/mirrors/prometheus-mirror: ./develop/mirrors/prometheus-mirror.md
  integrations/sdk: ./stackpacks/sdk.md
  setup/download: ./setup/linux_install/download.md
  setup/installation/authentication: ./setup/authentication.md
  setup/installation/development-installation: ./setup/linux_install/development-installation.md
  setup/installation/development-installation_pre1_15: ./setup/upgrading
  setup/installation/how_to_setup_tls_without_reverse_proxy: ./setup/linux_install/how_to_setup_tls_without_reverse_proxy.md
  setup/installation/index: ./setup/linux_install/index.md
  setup/installation/install_stackstate: ./setup/linux_install/install_stackstate.md
  setup/installation/installing_pre1_14_5: ./setup/upgrading.md
  setup/installation/installing_pre1_15: ./setup/upgrading.md
  setup/installation/kubernetes/image_configuration: ./setup/kubernetes_install/image_configuration.md
  setup/installation/kubernetes/ingress: ./setup/installation/kubernetes_install/ingress.md
  setup/installation/kubernetes/README: ./setup/kubernetes_install/README.md
  setup/installation/kubernetes/storage: ./setup/kubernetes_install/storage.md
  setup/installation/poc-installation: ./setup/linux_install/poc-installation.md
  setup/installation/production-installation: ./setup/linux_install/production-installation.md
  setup/installation/production-installation_pre1_15: ./setup/upgrading.md
  setup/installation/README: ./setup/linux_install/index.md
  setup/installation/reindex: ./setup/troubleshooting.md
  setup/installation/requirements: ./setup/requirements.md
  setup/installation/reverse_proxy: ./setup/linux_install/reverse_proxy.md
  setup/installation/troubleshooting: ./setup/troubleshooting.md
  configure/component_actions: configure/topology/component_actions.md
  configure/how_to_configure_component_actions: configure/topology/how_to_configure_component_actions.md
  configure/sync: configure/topology/sync.md
  configure/how_to_create_manual_topology: configure/topology/how_to_create_manual_topology.md
  configure/debugging_topology_synchronization: configure/topology/debugging_topology_synchronization.md
  configure/naming_guide: configure/topology/naming_guide.md
  configure/propagation: configure/topology/propagation.md
  configure/tagging: configure/topology/tagging.md
  configure/topology_synchronization: configure/topology/topology_synchronization.md
  configure/telemetry_synchronized_topology: configure/telemetry/telemetry_synchronized_topology.md
  configure/browse_telemetry: configure/telemetry/browse_telemetry.md
  configure/checks_and_streams: configure/telemetry/checks_and_streams.md
  configure/send_telemetry: configure/telemetry/send_telemetry.md
  configure/how_to_use_the_priority_field_for_components: configure/telemetry/how_to_use_the_priority_field_for_components.md
  configure/how_to_setup_traces: configure/traces/how_to_setup_traces.md
  configure/configure_tracing: configure/traces/configure_tracing.md
  configure/how_to_configure_ldap_authentication: configure/security/how_to_configure_ldap_authentication.md
  configure/permissions: configure/security/permissions.md
  configure/how_to_set_up_roles: configure/security/how_to_set_up_roles.md
  configure/scopes_in_rbac: configure/security/scopes_in_rbac.md
  configure/subject_configuration: configure/security/subject_configuration.md
  configure/secrets_management: configure/security/secrets_management.md
  configure/how_to_set_up_a_security_backend_for_linux: configure/security/how_to_set_up_a_security_backend_for_linux.md
  configure/how_to_set_up_a_security_backend_for_windows: configure/security/how_to_set_up_a_security_backend_for_windows.md
  configure/stackstate_log_files: setup/stackstate_log_files.md