
redirects:
  develop/creating_stackpacks: ./develop/stackpack/README.md
  integrations/: ./stackpacks/README.md
  integrations/available_stackpacks/: ./stackpacks/README.md
  integrations/available_stackpacks/agent: ./stackpacks/integrations/agent.md
  integrations/available_stackpacks/api-integration: stackpacks/integrations/api-integration.md
  integrations/available_stackpacks/aws: ./stackpacks/integrations/aws.md
  integrations/available_stackpacks/azure: ./stackpacks/integrations/azure.md
  integrations/available_stackpacks/cloudera: ./stackpacks/integrations/cloudera.md
  integrations/available_stackpacks/customsync: ./stackpacks/integrations/customsync.md
  integrations/available_stackpacks/google_analytics: ./stackpacks/integrations/google_analytics.md
  integrations/available_stackpacks/humio: ./stackpacks/integrations/humio.md
  integrations/available_stackpacks/kubernetes: ./stackpacks/integrations/kubernetes.md
  integrations/available_stackpacks/logz: ./stackpacks/integrations/logz.md
  integrations/available_stackpacks/manualtopo: ./stackpacks/integrations/manualtopo.md
  integrations/available_stackpacks/nagios: ./stackpacks/integrations/nagios.md
  integrations/available_stackpacks/openshift: ./stackpacks/integrations/openshft.md
  integrations/available_stackpacks/sap: ./stackpacks/integrations/sap.md
  integrations/available_stackpacks/scom: ./stackpacks/integrations/scom.md
  integrations/available_stackpacks/servicenow: ./stackpacks/integrations/servicenow.md
  integrations/available_stackpacks/splunk: ./stackpacks/integrations/splunk/README.md
  integrations/available_stackpacks/splunk/splunk_event: ./stackpacks/integration/splunk/splunk_event.md
  integrations/available_stackpacks/splunk/splunk_metric: ./stackpacks/integrations/splunk/splunk_metric.md
  integrations/available_stackpacks/static_topology: ./stackpacks/integrations/static_topology.md
  integrations/available_stackpacks/vsphere: ./stackpacks/integrations/vsphere.md
  integrations/available_stackpacks/zabbixL: ./stackpacks/integrations/zabbix.md
  integrations/introduction: ./stackpacks/about-stackpacks.md
  integrations/mirrors: ./develop/mirrors/README.md
  integrations/mirrors/prometheus-mirror: ./develop/mirrors/prometheus-mirror.md
  integrations/sdk: ./stackpacks/sdk.md
  setup/download.md: ./setup/linux_install/download.md
  setup/installation/authentication.md: ./setup/authentication.md
  setup/installation/development-installation.md: ./setup/linux_install/development-installation.md
  setup/installation/development-installation_pre1_15.md: ./setup/upgrading
  setup/installation/how_to_setup_tls_without_reverse_proxy.md: ./setup/linux_install/how_to_setup_tls_without_reverse_proxy.md
  setup/installation/index.md: ./setup/linux_install/index.md
  setup/installation/install_stackstate.md: ./setup/linux_install/install_stackstate.md
  setup/installation/installing_pre1_14_5.md: ./setup/upgrading
  setup/installation/installing_pre1_15.md: ./setup/upgrading
  setup/installation/kubernetes/image_configuration.md: ./setup/kubernetes_install/image_configuration.md
  setup/installation/kubernetes/ingress.md: ./setup/installation/kubernetes_install/ingress.md
  setup/installation/kubernetes/README.md: ./setup/kubernetes_install/README.md
  setup/installation/kubernetes/storage.md: ./setup/kubernetes_install/storage.md
  setup/installation/poc-installation.md: ./setup/linux_install/poc-installation.md
  setup/installation/production-installation.md: ./setup/linux_install/production-installation.md
  setup/installation/production-installation_pre1_15.md: ./setup/upgrading
  setup/installation/README.md: ./setup/linux_install/index.md
  setup/installation/reindex.md: ./setup/troubleshooting.md
  setup/installation/requirements.md: ./setup/requirements.md
  setup/installation/reverse_proxy.md: ./setup/linux_install/reverse_proxy.md
  setup/installation/troubleshooting.md: ./setup/troubleshooting.md
