
redirects:
  develop/creating_stackpacks/: ./develop/stackpack/README.md
  integrations/: ./v/4-0-0/integrations/
  integrations/available_stackpacks/: ./v/4-0-0/integrations/available_stackpacks/
  integrations/sdk: ./v/4-0-0/ntegrations/sdk.md
  integrations/introduction: ./v/4-0-0/integrations/introduction.md
  integrations/mirrors: ./v/4-0-0/integrations/mirrors/
  integrations/mirrors/prometheus-mirror: ./v/4-0-0/integrations/mirrors/prometheus-mirror.md
  integrations/available_stackpacks/agent: ./v/4-0-0/integrations/available_stackpacks/agent.md
  integrations/available_stackpacks/aws: ./v/4-0-0/integrations/available_stackpacks/aws.md
  integrations/available_stackpacks/azure: ./v/4-0-0/integrations/available_stackpacks/azure.md
  integrations/available_stackpacks/api-integration: ./v/4-0-0/integrations/available_stackpacks/api-integration.md
  integrations/available_stackpacks/cloudera: ./v/4-0-0/integrations/available_stackpacks/cloudera.md
  integrations/available_stackpacks/customsync: ./v/4-0-0/integrations/available_stackpacks/customsync.md
  integrations/available_stackpacks/google_analytics: ./v/4-0-0/integrations/available_stackpacks/google_analytics.md
  integrations/available_stackpacks/humio: ./v/4-0-0/integrations/available_stackpacks/humi.md
  integrations/available_stackpacks/kubernetes: ./v/4-0-0/integrations/available_stackpacks/kubernetes.md
  integrations/available_stackpacks/logz: ./v/4-0-0/integrations/available_stackpacks/logz.md
  integrations/available_stackpacks/manualtopo: ./v/4-0-0/integrations/available_stackpacks/manualtopo.md
  integrations/available_stackpacks/nagios: ./v/4-0-0/integrations/available_stackpacks/nagios.md
  integrations/available_stackpacks/openshift: ./v/4-0-0/integrations/available_stackpacks/openshift.md
  integrations/available_stackpacks/sap: ./v/4-0-0/integrations/available_stackpacks/sap.md
  integrations/available_stackpacks/scom: ./v/4-0-0/integrations/available_stackpacks/scom.md
  integrations/available_stackpacks/servicenow: ./v/4-0-0/integrations/available_stackpacks/servicenow.md
  integrations/available_stackpacks/splunk: ./v/4-0-0/integrations/available_stackpacks/splunk.md
  integrations/available_stackpacks/splunk/splunk_metric: ./v/4-0-0/integrations/available_stackpacks/splunk/splunk_metric.md
  integrations/available_stackpacks/splunk/splunk_event: ./v/4-0-0/integrations/available_stackpacks/splunk/splunk_event.md
  integrations/available_stackpacks/static_topology: ./v/4-0-0/integrations/available_stackpacks/static_topology.md
  integrations/available_stackpacks/vsphere: ./v/4-0-0/integrations/available_stackpacks/vsphere.md
  integrations/available_stackpacks/zabbixL: ./v/4-0-0/integrations/available_stackpacks/zabbixL.md
